Repository akai-org/planer-podrozy, pull requests merged in 2023-05, with the labels that each got.

#79 Marker handler
  ui/src/components/Map/Map.jsx
Labels: enhancement, frontend

#77 Storybook: Button stories
  ui/.prettierrc.json
  ui/src/components/Button/Button.jsx
  ui/src/components/Button/Button.stories.jsx
Labels: documentation, frontend

#91 58 endpoint aktywacji konta
  .gitignore
  api/requirements/docker.txt
  api/src/api/config.py
  api/src/api/database.py
  api/src/api/databases.py
  api/src/auth/config.py
  api/src/auth/crud.py
  api/src/auth/exceptions.py
  api/src/auth/manager.py
  api/src/auth/models.py
  api/src/auth/router.py
  api/src/auth/router/__init__.py
  api/src/auth/router/auth.py
  api/src/auth/schemas.py
  api/src/auth/utils.py
  api/src/main.py
  deployment/backend.dev.env
  deployment/backend.template.dev.env
  deployment/database.dev.env
  deployment/database.template.dev.env
  deployment/frontend.dev.env
  deployment/frontend.template.dev.env
  docker-compose.yml
Labels: backend
